title: Modeling Conference Deadlines # (Maintained by @madhunimmo)

description: Countdowns to top PL and SE conference deadlines
author: Madhurima Chakraborty (forked from @zhangysh1995 who forked from @abhshkdz :P)
domain: ""
baseurl: "https://madhunimmo.github.io/plse-deadlines"

twitter_username: FriendingNimmo 
github_username: madhunimmo
github_repo: plse-deadlines

markdown: kramdown
ga_id: UA-36274081-2

include: ['_pages']
