title: Modeling Conference Deadlines # (Maintained by @judithmichael)

description: Countdowns to modeling conference deadlines
author: Judith Michael (forked from @madhunimmo who forked from @abhshkdz)
domain: ""
baseurl: "https://judithmichael.github.io/modeling-conf-deadlines/"

twitter_username: JudithMichael_
github_username: judithmichael
github_repo: modeling-conf-deadlines 

markdown: kramdown
ga_id:

include: ['_pages']

